import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
<<<<<<< HEAD
=======
import { Toaster } from "@/components/ui/sonner";
>>>>>>> 5bf1f5b (second)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SayHire-Ai Voice Agent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Provider>
          {children}
<<<<<<< HEAD
=======
          <Toaster/>
>>>>>>> 5bf1f5b (second)
      </Provider>
      </body>
    </html>
  );
}
